export const COMMON_SKILLS = [
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "GitHub Actions",
  "CI/CD",
  "Linux",
  "Bash",
  "PowerShell",
  "Networking",
  "Cybersecurity",
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "C#",
  "C++",
  "Go",
  "Rust",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Scala",
  "R",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "SQL Server",
  "MongoDB",
  "Redis",
  "Elasticsearch",
  "Firebase",
  "Prisma",
  "Node.js",
  "Express",
  "NestJS",
  "React",
  "Next.js",
  "Redux",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Sass",
  "Material UI",
  "Bootstrap",
  "Vite",
  "Webpack",
  "GraphQL",
  "REST API",
  "gRPC",
  "Apollo GraphQL",
  "React Native",
  "Flutter",
  "Android",
  "iOS",
  "Spring Boot",
  ".NET",
  "ASP.NET Core",
  "Hibernate",
  "Django",
  "FastAPI",
  "Flask",
  "Laravel",
  "Ruby on Rails",
  "Microservices",
  "Event-Driven Architecture",
  "System Design",
  "Data Structures",
  "Algorithms",
  "Unit Testing",
  "Integration Testing",
  "Playwright",
  "Cypress",
  "Selenium",
  "Jest",
  "Vitest",
  "Pytest",
  "JUnit",
  "Agile",
  "Scrum",
  "Kanban",
  "Product Management",
  "Business Analysis",
  "Figma",
  "UI Design",
  "UX Research",
  "Data Analysis",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Apache Spark",
  "Hadoop",
  "Airflow",
  "Kafka",
  "RabbitMQ",
  "Snowflake",
  "Databricks",
  "Tableau",
  "Power BI",
  "ETL",
  "Data Warehousing",
  "Salesforce",
  "ServiceNow",
  "SAP",
  "Testing Automation",
  "Performance Testing",
  "Accessibility",
  "SEO",
  "Content Strategy",
  "Technical Writing",
  "Stakeholder Management",
  "Project Management",
  "Communication",
  "Leadership",
] as const;
